// Stock importado desde "total inventario tiempo real.xlsx" (primeros 40 con precio válido)
import { estimateMonthlyAutofin } from "@/lib/finance/autofin";

export interface VehicleSpin {
  count: number;
  pattern?: string;
  ext?: string;
}

export interface Vehicle {
  slug: string;
  plate?: string;
  brand: string;
  model: string;
  version: string;
  year: number;
  price: number;
  listPrice?: number;
  km: number;
  fuel: string;
  transmission: string;
  bodyType: string;
  location: string;
  image: string;
  gallery?: string[];
  spin?: VehicleSpin;
  engine: string;
  power: string;
  traction: string;
  doors: number;
  owners: number;
  featured?: boolean;
  status?: "Disponible" | "En reserva" | "Vendido" | "Borrador" | "En preparación";
  hasRealPhotos?: boolean;
  /** Si true, el sync de Drive conserva esta portada (no vuelve a gallery[0]). */
  coverLocked?: boolean;
  supplier?: string;
  techReview?: string;
  circPermit?: string;
  highlights?: string[];
}

export const initialVehicles: Vehicle[] = [
  {
    "slug": "mitsubishi-katana-4x2-2024-thzf75",
    "plate": "THZF 75",
    "brand": "Mitsubishi",
    "model": "KATANA 4X2",
    "version": "KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 65000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-05.jpg",
    "gallery": [
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-05.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-02.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-03.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-04.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-06.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-07.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-08.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-09.jpg",
      "/cars/uploads/mitsubishi-katana-4x2-2024-thzf75/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.4L Biturbo Diésel",
    "power": "201 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-katana-work-4x2-2022-rggz96",
    "plate": "RGGZ 96",
    "brand": "Mitsubishi",
    "model": "KATANA WORK 4X2",
    "version": "KATANA WORK 4X2 · Blanco",
    "year": 2022,
    "price": 13990000,
    "listPrice": 14990000,
    "km": 148386,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-03.jpg",
    "gallery": [
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-03.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-02.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-04.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-05.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-06.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-07.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-08.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-09.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-10.jpg",
      "/cars/uploads/mitsubishi-katana-work-4x2-2022-rggz96/photo-11.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "152 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-pgbv10",
    "plate": "PGBV 10",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 12490000,
    "listPrice": 13990000,
    "km": 208401,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "152 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2021-rbfk40",
    "plate": "RBFK 40",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2021,
    "price": 11990000,
    "km": 182825,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "152 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-new-katana-crt-4x2-2019-kwrc91",
    "plate": "KWRC 91",
    "brand": "Mitsubishi",
    "model": "NEW KATANA CRT 4X2",
    "version": "NEW KATANA CRT 4X2 · Rojo",
    "year": 2019,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 389144,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-05.jpg",
    "gallery": [
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-05.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-02.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-03.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-04.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-06.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-07.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-08.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-09.jpg",
      "/cars/uploads/mitsubishi-new-katana-crt-4x2-2019-kwrc91/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "152 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-l200-work-4x2-2021-pxsv97",
    "plate": "PXSV 97",
    "brand": "Mitsubishi",
    "model": "L200 WORK 4X2",
    "version": "L200 WORK 4X2 · Rojo",
    "year": 2021,
    "price": 12490000,
    "listPrice": 13490000,
    "km": 139113,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-02.jpg",
    "gallery": [
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-02.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-03.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-04.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-05.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-06.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-07.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-08.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-09.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-10.jpg",
      "/cars/uploads/mitsubishi-l200-work-4x2-2021-pxsv97/photo-11.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "152 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": true,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x4-2020-pgbv11",
    "plate": "PGBV 11",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X4",
    "version": "L200 KATANA 4X4 · Rojo",
    "year": 2020,
    "price": 12990000,
    "km": 129304,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-03.jpg",
    "gallery": [
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-03.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-02.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-04.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-05.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-06.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-07.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-08.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-09.jpg",
      "/cars/uploads/mitsubishi-l200-katana-4x4-2020-pgbv11/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "152 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mitsubishi-l200-katana-4x2-2024-thlv62",
    "plate": "THLV 62",
    "brand": "Mitsubishi",
    "model": "L200 KATANA 4X2",
    "version": "L200 KATANA 4X2 · Rojo",
    "year": 2024,
    "price": 14990000,
    "km": 69749,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.4L Biturbo Diésel",
    "power": "201 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "toyota-hilux-4x2-2023-swdv33",
    "plate": "SWDV 33",
    "brand": "Toyota",
    "model": "HILUX 4X2",
    "version": "HILUX 4X2 · Rojo",
    "year": 2023,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 159378,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-07.jpg",
    "gallery": [
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-07.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-02.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-03.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-04.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-05.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-06.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-08.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-09.jpg",
      "/cars/uploads/toyota-hilux-4x2-2023-swdv33/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "148 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "toyota-hilux-sr-4x4-2022-rwyr12",
    "plate": "RWYR 12",
    "brand": "Toyota",
    "model": "HILUX SR 4X4",
    "version": "HILUX SR 4X4 · Rojo",
    "year": 2022,
    "price": 22990000,
    "listPrice": 23990000,
    "km": 84000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-02.jpg",
    "gallery": [
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-02.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-03.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-04.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-05.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-06.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-07.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-08.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-09.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2022-rwyr12/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.8L Turbo Diésel",
    "power": "201 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "toyota-hilux-sr-4x4-2024-thsr65",
    "plate": "THSR 65",
    "brand": "Toyota",
    "model": "HILUX SR 4X4",
    "version": "HILUX SR 4X4 · Roja",
    "year": 2024,
    "price": 24990000,
    "listPrice": 25990000,
    "km": 90386,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-02.jpg",
    "gallery": [
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-02.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-03.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-04.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-05.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-06.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-07.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-08.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-09.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-10.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-11.jpg",
      "/cars/uploads/toyota-hilux-sr-4x4-2024-thsr65/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.8L Turbo Diésel",
    "power": "201 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "toyota-hilux-4x4-2022-rzvl18",
    "plate": "RZVL 18",
    "brand": "Toyota",
    "model": "HILUX 4X4",
    "version": "HILUX 4X4 · Rojo",
    "year": 2022,
    "price": 16990000,
    "km": 127576,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "148 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "toyota-hilux-dx-4x4-2021-pskj78",
    "plate": "PSKJ 78",
    "brand": "Toyota",
    "model": "HILUX DX 4X4",
    "version": "HILUX DX 4X4 · Rojo",
    "year": 2021,
    "price": 14990000,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/placeholder-vehicle.jpg",
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.4L Turbo Diésel",
    "power": "148 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "peugeot-partner-hdi-92-l1-1-6-2022-sbzc70",
    "plate": "SBZC 70",
    "brand": "Peugeot",
    "model": "PARTNER HDI 92 L1 1.6",
    "version": "PARTNER HDI 92 L1 1.6 · Blanco",
    "year": 2022,
    "price": 8290000,
    "listPrice": 9290000,
    "km": 150104,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-02.jpg",
    "gallery": [
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-02.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-03.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-04.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-05.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-06.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-07.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-08.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-09.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-10.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-11.jpg",
      "/cars/uploads/peugeot-partner-hdi-92-l1-1-6-2022-sbzc70/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "1.6L BlueHDi",
    "power": "92 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "peugeot-partner-2022-rlvr63",
    "plate": "RLVR 63",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2022,
    "price": 7990000,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/placeholder-vehicle.jpg",
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "1.5L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "peugeot-partner-1-5-2023-svfb26",
    "plate": "SVFB 26",
    "brand": "Peugeot",
    "model": "PARTNER 1.5",
    "version": "PARTNER 1.5 · Blanco",
    "year": 2023,
    "price": 10490000,
    "km": 89498,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "1.5L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "peugeot-expert-2022-scdw37",
    "plate": "SCDW 37",
    "brand": "Peugeot",
    "model": "EXPERT",
    "version": "EXPERT · Blanco",
    "year": 2022,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 236400,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/peugeot-expert-2022-scdw37/photo-05.jpg",
    "gallery": [
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-05.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-02.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-03.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-04.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-06.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-07.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-08.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-09.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-10.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-11.jpg",
      "/cars/uploads/peugeot-expert-2022-scdw37/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.0L BlueHDi",
    "power": "120 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "peugeot-partner-2023-ssdd57",
    "plate": "SSDD 57",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2023,
    "price": 9990000,
    "km": 152557,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/peugeot-partner-2023-ssdd57/photo-04.jpg",
    "gallery": [
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-04.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-02.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-03.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-05.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-06.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-07.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-08.jpg",
      "/cars/uploads/peugeot-partner-2023-ssdd57/photo-09.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "1.5L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "nissan-navara-xe-4x2-2024-tcgb98",
    "plate": "TCGB 98",
    "brand": "Nissan",
    "model": "NAVARA XE 4X2",
    "version": "NAVARA XE 4X2 · Roja",
    "year": 2024,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 125518,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-06.jpg",
    "gallery": [
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-06.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-02.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-03.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-04.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-05.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-07.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-08.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-09.jpg",
      "/cars/uploads/nissan-navara-xe-4x2-2024-tcgb98/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.3L Bi-Turbo Diésel",
    "power": "190 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "nissan-navara-4x2-2024-tcpt20",
    "plate": "TCPT 20",
    "brand": "Nissan",
    "model": "NAVARA 4X2",
    "version": "NAVARA 4X2 · Rojo",
    "year": 2024,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 51714,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-04.jpg",
    "gallery": [
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-04.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-02.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-03.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-05.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-06.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-07.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-08.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-09.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-10.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-11.jpg",
      "/cars/uploads/nissan-navara-4x2-2024-tcpt20/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.3L Bi-Turbo Diésel",
    "power": "190 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "ford-raptor-f150-2020-lrjy32",
    "plate": "LRJY 32",
    "brand": "Ford",
    "model": "RAPTOR F150",
    "version": "RAPTOR F150 · Rojo",
    "year": 2020,
    "price": 39990000,
    "km": 136279,
    "fuel": "Bencina",
    "transmission": "Automática",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-02.jpg",
    "gallery": [
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-02.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-03.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-04.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-05.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-06.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-07.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-08.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-09.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-10.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-11.jpg",
      "/cars/uploads/ford-raptor-f150-2020-lrjy32/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "3.5L V6 EcoBoost Twin-Turbo",
    "power": "450 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "volkswagen-saveiro-dcab-2023-sfrx48",
    "plate": "SFRX 48",
    "brand": "Volkswagen",
    "model": "SAVEIRO DCAB",
    "version": "SAVEIRO DCAB · Blanco",
    "year": 2023,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 59000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-08.jpg",
    "gallery": [
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-08.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-02.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-03.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-04.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-05.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-06.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-07.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-09.jpg",
      "/cars/uploads/volkswagen-saveiro-dcab-2023-sfrx48/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "1.6L MSI",
    "power": "110 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "volkswagen-saveiro-cd-1-6-2022-slgd85",
    "plate": "SLGD 85",
    "brand": "Volkswagen",
    "model": "SAVEIRO CD 1.6",
    "version": "SAVEIRO CD 1.6 · Blanco",
    "year": 2022,
    "price": 9990000,
    "km": 8065,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-03.jpg",
    "gallery": [
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-03.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-02.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-04.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-05.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-06.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-07.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-08.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-09.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-10.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-11.jpg",
      "/cars/uploads/volkswagen-saveiro-cd-1-6-2022-slgd85/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "1.6L MSI",
    "power": "110 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "volkswagen-amarok-4x4-mt-2022-rrkb78",
    "plate": "RRKB 78",
    "brand": "Volkswagen",
    "model": "AMAROK 4X4 MT",
    "version": "AMAROK 4X4 MT · Blanco",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 207000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-08.jpg",
    "gallery": [
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-08.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-02.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-03.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-04.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-05.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-06.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-07.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-09.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-10.jpg",
      "/cars/uploads/volkswagen-amarok-4x4-mt-2022-rrkb78/photo-11.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.0L BiTDI Diésel",
    "power": "180 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "hino-xzu-617-dc-2023-sklf13",
    "plate": "SKLF 13",
    "brand": "Hino",
    "model": "XZU 617 DC",
    "version": "XZU 617 DC · Blanco",
    "year": 2023,
    "price": 25990000,
    "listPrice": 26990000,
    "km": 103000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-03.jpg",
    "gallery": [
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-03.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-02.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-04.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-05.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-06.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-07.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-08.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-09.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-10.jpg",
      "/cars/uploads/hino-xzu-617-dc-2023-sklf13/photo-11.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "4.0L Diésel",
    "power": "150 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "maxus-t60-4x4-glx-2022-sdds52",
    "plate": "SDDS 52",
    "brand": "Maxus",
    "model": "T60 4X4 GLX",
    "version": "T60 4X4 GLX · Blanco",
    "year": 2022,
    "price": 10990000,
    "listPrice": 11990000,
    "km": 190305,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-03.jpg",
    "gallery": [
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-03.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-02.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-04.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-05.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-06.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-07.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-08.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-09.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-10.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-11.jpg",
      "/cars/uploads/maxus-t60-4x4-glx-2022-sdds52/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.0L Turbo Diésel",
    "power": "163 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "maxus-t60-4x2-2022-sfwd31",
    "plate": "SFWD 31",
    "brand": "Maxus",
    "model": "T60 4X2",
    "version": "T60 4X2 · Blanco",
    "year": 2022,
    "price": 9990000,
    "listPrice": 10990000,
    "km": 69379,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.0L Turbo Diésel",
    "power": "163 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "toyota-raize-4x2-1-2-2025-tsgl82",
    "plate": "TSGL 82",
    "brand": "Toyota",
    "model": "RAIZE 4X2 1.2",
    "version": "RAIZE 4X2 1.2 · Gris",
    "year": 2025,
    "price": 11990000,
    "listPrice": 13490000,
    "km": 16000,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "SUV",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-08.jpg",
    "gallery": [
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-08.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-02.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-03.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-04.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-05.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-06.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-07.jpg",
      "/cars/uploads/toyota-raize-4x2-1-2-2025-tsgl82/photo-09.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "1.2L Dual VVT-i",
    "power": "87 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sfyb29",
    "plate": "SFYB 29",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 18990000,
    "listPrice": 19990000,
    "km": 111222,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-07.jpg",
    "gallery": [
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-07.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-02.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-03.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-04.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-05.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-06.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-08.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-09.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfyb29/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sfbl43",
    "plate": "SFBL 43",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 16990000,
    "listPrice": 17990000,
    "km": 149586,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-01.jpg",
    "gallery": [
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-01.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-02.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-03.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-04.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-05.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-06.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-07.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-08.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-09.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-10.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-11.jpg",
      "/cars/uploads/chevrolet-colorado-4x4-aut-2022-sfbl43/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "chevrolet-colorado-4x4-aut-2022-sdjt43",
    "plate": "SDJT 43",
    "brand": "Chevrolet",
    "model": "COLORADO 4X4 AUT.",
    "version": "COLORADO 4X4 AUT. · Blanco",
    "year": 2022,
    "price": 15990000,
    "listPrice": 16990000,
    "km": 177865,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.8L Duramax Turbo Diésel",
    "power": "200 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "chevrolet-dmax-4x4-2022-rpfs85",
    "plate": "RPFS 85",
    "brand": "Chevrolet",
    "model": "DMAX 4X4",
    "version": "DMAX 4X4 · Rojo",
    "year": 2022,
    "price": 13990000,
    "listPrice": 14990000,
    "km": 0,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/images/placeholder-pending-car.svg",
    "gallery": [],
    "hasRealPhotos": false,
    "status": "Disponible",
    "engine": "2.5L Turbo Diésel",
    "power": "163 HP",
    "traction": "4x4",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "mercedes-benz-ml300-cdi-2011-ddlj95",
    "plate": "DDLJ 95",
    "brand": "Mercedes-Benz",
    "model": "ML300 CDI",
    "version": "ML300 CDI · Blanco",
    "year": 2011,
    "price": 9490000,
    "listPrice": 10490000,
    "km": 216000,
    "fuel": "Diésel",
    "transmission": "Automática",
    "bodyType": "SUV",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-02.jpg",
    "gallery": [
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-02.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-03.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-04.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-05.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-06.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-07.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-08.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-09.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-10.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-11.jpg",
      "/cars/uploads/mercedes-benz-ml300-cdi-2011-ddlj95/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "3.0L V6 CDI Diésel",
    "power": "190 HP",
    "traction": "4x4",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "subaru-wrx-sti-4x4-2-5-2022-rkrg58",
    "plate": "RKRG 58",
    "brand": "Subaru",
    "model": "WRX STI 4X4 2.5",
    "version": "WRX STI 4X4 2.5 · Azul",
    "year": 2022,
    "price": 39990000,
    "listPrice": 40990000,
    "km": 0,
    "fuel": "Bencina",
    "transmission": "Manual",
    "bodyType": "Sedán",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-02.jpg",
    "gallery": [
      "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-02.jpg",
      "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-03.jpg",
      "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-04.jpg",
      "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-05.jpg",
      "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-06.jpg",
      "/cars/uploads/subaru-wrx-sti-4x4-2-5-2022-rkrg58/photo-07.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.5L Boxer Turbo",
    "power": "300 HP",
    "traction": "AWD",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "hyundai-porter-ii-2022-rpsh45",
    "plate": "RPSH 45",
    "brand": "Hyundai",
    "model": "PORTER II",
    "version": "PORTER II · Blanco",
    "year": 2022,
    "price": 14990000,
    "listPrice": 15990000,
    "km": 110000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camión",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-02.jpg",
    "gallery": [
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-02.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-03.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-04.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-05.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-06.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-07.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-08.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-09.jpg",
      "/cars/uploads/hyundai-porter-ii-2022-rpsh45/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.5L CRDi Diésel",
    "power": "130 HP",
    "traction": "4x2",
    "doors": 2,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "peugeot-partner-2021-psjj97",
    "plate": "PSJJ 97",
    "brand": "Peugeot",
    "model": "PARTNER",
    "version": "PARTNER · Blanco",
    "year": 2021,
    "price": 8990000,
    "listPrice": 10490000,
    "km": 104900,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Furgón",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/peugeot-partner-2021-psjj97/photo-07.jpg",
    "gallery": [
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-07.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-02.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-03.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-04.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-05.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-06.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-08.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-09.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-10.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-11.jpg",
      "/cars/uploads/peugeot-partner-2021-psjj97/photo-12.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "1.5L BlueHDi",
    "power": "100 HP",
    "traction": "4x2",
    "doors": 5,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  },
  {
    "slug": "nissan-navara-4x2-2023-sjtd29",
    "plate": "SJTD 29",
    "brand": "Nissan",
    "model": "NAVARA 4X2",
    "version": "NAVARA 4X2 · Gris",
    "year": 2023,
    "price": 15990000,
    "listPrice": 17990000,
    "km": 80000,
    "fuel": "Diésel",
    "transmission": "Manual",
    "bodyType": "Camioneta",
    "location": "Puerto Montt · Av. El Tepual",
    "image": "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-03.jpg",
    "gallery": [
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-03.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-02.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-04.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-05.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-06.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-07.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-08.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-09.jpg",
      "/cars/uploads/nissan-navara-4x2-2023-sjtd29/photo-10.jpg"
    ],
    "hasRealPhotos": true,
    "status": "Disponible",
    "engine": "2.3L Bi-Turbo Diésel",
    "power": "190 HP",
    "traction": "4x2",
    "doors": 4,
    "owners": 1,
    "featured": false,
    "highlights": [
      "Unidad del inventario actual RG Motors",
      "Fotos reales de patio cuando estén disponibles",
      "Financiamiento Autofin referencial"
    ]
  }
];

export const HERO_SHOWCASE_VEHICLES: Vehicle[] = initialVehicles
  .filter((v) => v.featured && v.hasRealPhotos)
  .slice(0, 6);

export const vehicles: Vehicle[] = initialVehicles;

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function formatCLP(amount: number): string {
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatKm(km: number): string {
  return `${km.toLocaleString("es-CL")} km`;
}

export function estimateMonthly(price: number, termMonths = 48, piePercent = 0.2): number {
  return estimateMonthlyAutofin(price, termMonths, piePercent);
}

export function spinFramesOf(v: Vehicle): string[] {
  if (!v.spin || v.spin.count <= 0) return [];
  const ext = v.spin.ext ?? "jpg";
  const pattern = v.spin.pattern ?? `/cars/spin/${v.slug}/{i}.${ext}`;
  return Array.from({ length: v.spin.count }, (_, i) =>
    pattern.replace("{i}", String(i + 1).padStart(3, "0")),
  );
}

export function specsOf(v: Vehicle): { label: string; value: string }[] {
  return [
    { label: "Motor", value: v.engine || "—" },
    { label: "Potencia", value: v.power || "—" },
    { label: "Transmisión", value: v.transmission || "—" },
    { label: "Tracción", value: v.traction || "—" },
    { label: "Combustible", value: v.fuel || "—" },
    { label: "Puertas", value: v.doors != null ? String(v.doors) : "—" },
  ];
}

export const BRANDS = [...new Set(vehicles.map((v) => v.brand))].sort();
export const BODY_TYPES = [...new Set(vehicles.map((v) => v.bodyType))];
export const FUELS = [...new Set(vehicles.map((v) => v.fuel))];
export const TRANSMISSIONS = [...new Set(vehicles.map((v) => v.transmission))];
export const STATUS_TYPES = ["Disponible", "En reserva", "Vendido", "Borrador", "En preparación"] as const;
